---

- name: crerate ec2 instance
  hosts: localhost
  gather_facts: no
  tasks:
  - name: create security group
    ec2_group: 
      name: joyfru-core-test
      description: joyfru-core-test
      region: ap-northeast-1
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      rules_egress:
      - proto: all
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0
  - name: create ec2 instance
    ec2:
      image: ami-29d1e34e
      instance_type: t2.micro
      region: ap-northeast-1
      key_name: surface
      group: joyfru-core-test
      instance_tags:
        Name: joyfru-core-test
        Group: johyfru-core-test
      wait: yes
      wait_timeout: 300
      volumes:
      - device_name: "/dev/xvda"
        device_type: gp2
        volume_size: 10
        delete_on_termination: yes
    register: ec2
  - name: wait for SSH connectable
    wait_for:
      port: 22
      host: "{{item.public_ip}}"
      timeout: 300
      state: started
    with_items: ec2.instances
  - name: add inventory
    add_host:
      host_name: "{{ item.public_ip }}"
      groupname: "tag_Group_joyfru-core-test"
    with_items: ec2.instaces

- name: provisioning ec2 instance
  hosts: tag_Group_joyfru-core-test
  remote_user: centos
  become: yes
  become_method: sudo
  roles:
    - role: common/nginx-install

