---

- hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  vars_files:
    - secrets/secret_vars.yml
  vars:
    aws_default_region: ap-northeast-1
    aws_s3_bugget_name: your-bugget-name
  roles:
    - role: app/goofys
    - role: common/mounts3
