---

- name: install golang
  yum:
    name: golang
    state: removed

- name: create directory
  file:
    path: /tmp/.golang-install
    state: directory

- name: download golang ver1.8
  get_url:
    url: https://storage.googleapis.com/golang/go1.8.3.linux-amd64.tar.gz
    dest: /tmp/.golang-install/go1.8.3.linux-amd64.tar.gz

- name: unpack and install golang
  shell: tar -C /usr/local -xzf /tmp/.golang-install/go1.8.3.linux-amd64.tar.gz

- name: install fuse
  yum:
    name: fuse
    state: installed

- name: download and install goofys
  get_url:
    url: https://github.com/kahing/goofys/releases/download/v0.0.13/goofys
    dest: /usr/local/bin/goofys
    mode: 0755
